# Generated by Django 4.1.4 on 2023-01-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sign_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_Up',
        ),
    ]
