# Generated by Django 4.1.4 on 2023-01-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_firs_name_bloguser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_in', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bloguser')),
            ],
        ),
    ]
