# Generated by Django 4.1.4 on 2023-04-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_log_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
